[package]
name = "bench-new"
version = "0.1.0"
edition = "2024"

[dependencies]
bench-common = { path = "../bench-common" }
deltalake = "0.30.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

# Needed because main.rs uses the async_trait attribute and url::Url in signatures

async-trait = "0.1"
url = "2"